nome = input('Digite seu nome completo: ')
print(f'O seu nome somente em letras maiúsculas é: {nome.upper()}')
print(f'O seu nome somente em minúsculas é: {nome. lower()}')
dividido = nome.split()
print(f'Seu primeiro nome é {dividido[0]} e ele tem: {len(dividido [0])} letras')
sem = nome.replace(' ', '')
print(f'A quantidade de letras no seu nome é: {len(sem)}')
